# Generated by Django 3.2.4 on 2022-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220124_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='923cad35-b5d2-4f34-99fc-8bcb311be726', max_length=36, unique=True),
        ),
    ]
