# Generated by Django 3.2.4 on 2022-04-29 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220429_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=256, unique=True),
        ),
    ]
