# Generated by Django 3.2.4 on 2022-02-09 10:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_auto_20220205_2106'),
        ('account', '0002_auto_20220124_1915'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(blank=True, max_length=36, unique=True)),
                ('status', models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled'), ('Shipped', 'Shipped'), ('Received', 'Received')], default='unfulfilled', max_length=32)),
                ('price', models.FloatField(blank=True, null=True)),
                ('paid_price', models.FloatField(default=0.0)),
                ('is_delete', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiy', models.PositiveIntegerField(verbose_name=[django.core.validators.MinValueValidator(1)])),
                ('price', models.FloatField(default=0.0)),
                ('real_price', models.FloatField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.productvariants')),
            ],
        ),
    ]
