# Generated by Django 3.2.4 on 2022-04-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ('pk',)},
        ),
    ]
