# Generated by Django 3.2.4 on 2022-05-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220404_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
