# Generated by Django 3.2.4 on 2022-02-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',)},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='backgroud_image',
            new_name='background_image',
        ),
    ]
