# Generated by Django 3.2.4 on 2022-02-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='money',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
