# Generated by Django 3.2.4 on 2022-02-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='menthod',
            new_name='method',
        ),
    ]
