# Generated by Django 3.2.4 on 2022-01-28 12:08

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('product_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='product')),
                ('is_delete', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='category.category')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('productVariant_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='productVariant')),
                ('is_delete', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.products')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
