# Generated by Django 3.2.4 on 2022-01-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productVariants', to='product.products'),
        ),
    ]
