# Generated by Django 3.2.4 on 2022-05-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220404_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-pk',)},
        ),
    ]
